apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: superset-pod
  name: superset-pod
  namespace: default
spec:
  containers:
  - image: us-central1-docker.pkg.dev/sqsh-developer-pocs/superset-repo/superset-v2:$COMMIT_SHA
    name: superset-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: superset-service
  namespace: default
spec:
  selector:
    run: superset-pod
  type: LoadBalancer
  # loadBalancerIP: <static-ip-with-premium-tier>
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8088